
version: '3'

services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "chown -R www-data:www-data /var/www && chmod -R 755 /var/www/storage && php-fpm"
    image: my-laravel-app
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
        - ./:/var/www
    networks:
      - app-network

  # MySQL Service
  database:
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql/

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

# Volumes
volumes:
  dbdata:

# Networks Configuration
networks:
  app-network:
    driver: bridge
